apiVersion: metal3.io/v1alpha1
kind: HostFirmwareComponents
metadata:
  labels:
    app.kubernetes.io/name: hostfirmwarecomponents
    app.kubernetes.io/instance: hostfirmwarecomponents-sample
    app.kubernetes.io/part-of: baremetal-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: baremetal-operator
  name: hostfirmwarecomponents-sample
spec:
  updates:
  - name: bios
    url: https://myurl.with.firmware.for.bios
  - name: bmc
    url: https://myurl.with.firmware.for.bmc
status:
  components:
  - component: bios
    initialVersion: "v1.0.0"
    currentVersion: "v1.5.0"
    lastVersionFlashed: "v1.5.0"
    updatedAt: "2023-10-13T13:50:06Z"
  - component: bmc
    initialVersion: "v1.0.5"
    currentVersion: "v1.2.0"
    lastVersionFlashed: "v1.2.0"
    updatedAt: "2023-10-13T13:50:06Z"
  updates:
  - name: bios
    url: https://myurl.with.firmware.for.bios
  - name: bmc
    url: https://myurl.with.firmware.for.bmc
  lastUpdated: "2023-10-13T13:50:06Z"
